version: '3.4'

services:
  livraria:
    image: ${DOCKER_REGISTRY-}livraria
    build:
      context: .
      dockerfile: Livraria/Dockerfile
    ports:
      - "8081:80"
    depends_on:
      - sqldata

  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=123@Mudar
      - ACCEPT_EULA=Y
    volumes:
      - c:\dados\volumes\mssql:/var/opt/mssql/data
    ports:
      - "1450:1433"
